#
# (c) 2006 - 2008 EPFL, Lausanne, Switzerland
# Thomas Lochmatter
#

# List of standard modules that this program needs
MODULES	:= windsensorboard commandline i2c_stream i2cal measurement

# List of modules that you created on your own (and path to your modules)
#MY_MODULES	:= ../../Khepera3Modules/windsensorboard

# The file name of the executable
TARGET	:= windsensorboard_ntc_normalized

# If the K3_ROOT environment variable is set, you can comment out the following line
#K3_ROOT	:= /Users/thomas/svn/khepera3toolbox/Scripts/..

# Include the Makefile
include $(K3_ROOT)/Programs/Makefile.include
