#
# (c) 2006 - 2008 EPFL, Lausanne, Switzerland
# Thomas Lochmatter
#

# The list of modules that this program needs
MODULES	:= odometry_track odometry_goto khepera3 i2cal commandline nmea

# The file name of the executable
TARGET	:= odometry_goto

# If the K3_ROOT environment variable is set, you can comment out the following line
K3_ROOT	:= ../..

# Include the Makefile
include $(K3_ROOT)/Programs/Makefile.include
