#
# (c) 2006 - 2008 EPFL, Lausanne, Switzerland
# Thomas Lochmatter
#

# List of standard modules that this program needs
MODULES	:= khepera4 commandline i2cal

# List of modules that you created on your own (and path to your modules)
#MY_MODULES	:=

# The file name of the executable
TARGET	:= template

# If the K4_ROOT environment variable is set, you can comment out the following line
K4_ROOT	:= ../..

# Include the Makefile
include $(K4_ROOT)/Programs/Makefile.include
