#! /usr/bin/perl

# Configuration
my $ssh='/usr/bin/ssh';
my $sshhost=(shift || '192.168.1.2');
my $sshuserhost='root@'.$sshhost;

# Say what we are doing
print STDERR '=== Fetching robot id from ', $sshhost, ' ===', "\n";

# Get robot id
my $robotid=`$ssh $sshuserhost 'cat /etc/khepera/robotid'`;
print $robotid;
