#! /usr/bin/perl
use strict;

# Khepera III Toolbox / Install Scripts
# Author: Thomas Lochmatter, thomas.lochmatter@epfl.ch

# Configuration
my $ssh='/usr/bin/ssh';
my $scp='/usr/bin/scp';
my $sshhost=(shift || '192.168.1.2');
my $sshuserhost='root@'.$sshhost;

my $robotid=int(shift);
die 'Usage ./install_robotid.pl SSHHOST ROBOTID' if (! $robotid);

# Say what we are doing
print '=== Configuring robot id ', $robotid, ' on ', $sshhost, ' ===', "\n";

# Set up robot id
system($ssh, $sshuserhost, 'mkdir /etc/khepera');
system($ssh, $sshuserhost, 'echo "'.$robotid.'" > /etc/khepera/robotid') || die 'Could write robot id to /etc/khepera/robotid';
