#! /usr/bin/perl
use strict;

# Khepera III Toolbox / Install Scripts
# Author: Thomas Lochmatter, thomas.lochmatter@epfl.ch

# Configuration
my $ssh='/usr/bin/ssh';
my $scp='/usr/bin/scp';
my $sshhost=(shift || '192.168.1.2');
my $sshuserhost='root@'.$sshhost;
my $robotid=shift || die 'Usage: ./install_network.pl SSHHOST ROBOTID';

# Say what we are doing
print '=== Setting up network for robot ', $robotid, ' on ', $sshhost, ' ===', "\n";

# Modify interfaces configuration
open(IN, '<', 'network/interfaces-template');
open(OUT, '>', 'network/interfaces');
while (my $line=<IN>) {
	while (chomp $line) {}
	$line =~ s/ROBOTID/$robotid/g;
	print OUT $line, "\n";
}
close IN;
close OUT;

# Copy files and restart networking
system($scp, 'network/interfaces', $sshuserhost.':/etc/network/');
system($ssh, $sshuserhost, 'echo "pxa2xx_cs" > /etc/modutils/pxa2xx_cs') || die 'Could not create /etc/modutils/pxa2xx_cs';
system($ssh, $sshuserhost, 'echo "g_ether" > /etc/modutils/g_ether') || die 'Could not create /etc/modutils/g_ether';
system($ssh, $sshuserhost, '/usr/sbin/update-modules') && die 'Could not launch "update-modules"';
system($ssh, $sshuserhost, '/etc/init.d/networking restart') && die 'Could not launch "/etc/init.d/networking restart"';

# Delete temporary files
unlink 'network/interfaces';
