#! /usr/bin/perl
use strict;

# Khepera IV Toolbox / Install Scripts
# Author: Thomas Lochmatter, thomas.lochmatter@epfl.ch

# Configuration
my $ssh='/usr/bin/ssh';
my $scp='/usr/bin/scp';
my $sshhost=(shift || '192.168.1.2');
my $sshuserhost='root@'.$sshhost;

# Say what we are doing
print '=== Copying profile to ', $sshhost, ' ===', "\n";

# Copy files
system($ssh, $sshuserhost, 'mkdir /etc/profile.d');
system($scp, 'profile/khepera4toolbox', $sshuserhost.':/etc/profile.d/');
