#
# (c) 2009 EPFL, Lausanne, Switzerland
# Thomas Lochmatter
#

# The list of modules that this program needs
MODULES	:= commandline

# The file name of the executable
TARGET	:= cpu_performance

# If the K4_ROOT environment variable is set, you can comment out the following line
K4_ROOT	:= ../..

# Include the Makefile
include $(K4_ROOT)/Programs/Makefile.include
