#
# (c) 2006 - 2008 EPFL, Lausanne, Switzerland
# Thomas Lochmatter
#

# List of standard modules that this module needs
MODULES	:= i2cal i2c_stream

# List of modules that you created on your own (and path to your modules)
#MY_MODULES			:=
#MY_MODULES_FOLDER	:= ..

# The file name of the archive
ARCHIVE	:= odorboard.a

# If the K4_ROOT environment variable is set, you can comment out the following line
#K4_ROOT	:= /Users/thomas/svn/khepera4toolbox/Scripts/..

# Include the Makefile
include $(K4_ROOT)/Modules/Makefile.include
