#! /usr/bin/perl
use strict;

# Include the k3-commons file
my $basepath=($0 =~ /(.*)\/(.*?)/)[0];
require $basepath.'/k3-commons', 'INCLUDED';

# Parse the command line
while (my $cmd=shift) {
	if ($cmd =~ /^\+(.*)$/) {
		&robotlist_add($1);
	} else {
		&help();
	}
}

# Prepare and check
my @robotlist=&robotlist_get();
&help('No robots specified.') if (! scalar @robotlist);

# Read our SSH key
my $homefolder=$ENV{'HOME'};
open(F, $homefolder.'/.ssh/id_dsa.pub') || &help('SSH key (~/.ssh/id_dsa.pub) not found. Create one with "ssh-keygen -t dsa".');
my $key=<F>;
while (chomp $key) {}
close F;

# Send this key to all robots
foreach my $robotip (@robotlist) {
	&print_and_execute('ssh', 'root@'.$robotip, 'mkdir ~/.ssh; echo "'.$key.'" >> ~/.ssh/authorized_keys; sort -u ~/.ssh/authorized_keys > ~/.ssh/temp; mv ~/.ssh/temp ~/.ssh/authorized_keys');
}

# Help
sub help {
	if (my $err=shift) {
		print $err, "\n";
		print "\n";
	}

	print 'Adds your SSH key on the robots, so that you don\'t need to type the password any more.', "\n";
	print 'Usage: k3-ssh-keysetup +ROBOT1 +ROBOT2 ...', "\n";
	print '    +ROBOTx    Robot ID (e.g. 200), IP (e.g. 192.168.141.200) or name (e.g. bob)', "\n";
	exit(1);
}
