#! /usr/bin/perl
use strict;

# Include the k3-commons file
my $basepath=($0 =~ /(.*)\/(.*?)/)[0];
require $basepath.'/k3-commons', 'INCLUDED';

# Parse the command line
while (my $cmd=shift) {
	if ($cmd =~ /^\+(.*)$/) {
		&robotlist_add($1);
	} else {
		&help();
	}
}

# Prepare and check
my @robotlist=&robotlist_get();
&help('No robots specified.') if (! scalar @robotlist);

# Send the halt command to all robots
foreach my $robotip (@robotlist) {
	&print_and_execute('ssh', 'root@'.$robotip, 'halt');
}

# Help
sub help {
	if (my $err=shift) {
		print $err, "\n";
		print "\n";
	}

	print 'Shutdowns robots.', "\n";
	print 'Usage: k3halt +ROBOT1 +ROBOT2 ...', "\n";
	print '    +ROBOTx    Robot ID (e.g. 200), IP (e.g. 192.168.141.200) or name (e.g. bob)', "\n";
	exit(1);
}
