#! /usr/bin/perl
use strict;

# Include the k3-commons file
my $basepath=($0 =~ /(.*)\/(.*?)/)[0];
require $basepath.'/k3-commons', 'INCLUDED';

# Parse the command line
my @programs;
while (my $cmd=shift) {
	if ($cmd =~ /^\+(.*)$/) {
		&robotlist_add($1);
	} else {
		push @programs, $cmd;
	}
}

# Prepare and check
my @robotlist=&robotlist_get();
&help('No robots specified.') if (! scalar @robotlist);
&help('No programs specified.') if (! scalar @programs);

# Send the halt command to all robots
foreach my $robotip (@robotlist) {
	foreach my $program (@programs) {
		&print_and_execute('ssh', 'root@'.$robotip, 'killall '.$program);
	}
}

# Help
sub help {
	if (my $err=shift) {
		print $err, "\n";
		print "\n";
	}

	print 'Kills (stops) running programs on a fleet of robots.', "\n";
	print 'Usage: k3halt +ROBOT1 +ROBOT2 ... PROGRAM1 PROGRAM2 ...', "\n";
	print '    +ROBOTx    Robot ID (e.g. 200), IP (e.g. 192.168.141.200) or name (e.g. bob)', "\n";
	print '    PROGRAMx   The name of the program to kill', "\n";
	exit(1);
}
