#! /usr/bin/perl
use strict;

# Include the k3-commons file
my $basepath=($0 =~ /(.*)\/(.*?)/)[0];
require $basepath.'/k3-commons', 'INCLUDED';

# Parse the command line
my @files;
while (my $cmd=shift) {
	if ($cmd =~ /^\+(.*)$/) {
		&robotlist_add($1);
	} else {
		$cmd=$1 if ($cmd =~ /^(.*)\/+$/);
		my $file=$cmd;
		$file=$1 if ($file =~ /\/(.*?)$/);
		if (-f $cmd) {
			push @files, $cmd;
		} elsif (-f $cmd.'/'.$file) {
			push @files, $cmd.'/'.$file;
		} else {
			print 'File not found: ', $cmd, "\n";
			exit;
		}
	}
}

# Prepare and check
my $user=$ENV{'USER'} || 'unknown_user';
my @robotlist=&robotlist_get();
&help('No robots specified.') if (! scalar @robotlist);
&help('No files specified.') if (! scalar @files);

# Copy the files onto the robot.
foreach my $robotip (@robotlist) {
	&print_and_execute('ssh', '-f', 'root@'.$robotip, 'mkdir -p '.$user);
	foreach my $file (@files) {
		&print_and_execute('scp', $file, 'root@'.$robotip.':~/'.$user.'/'); # && die 'scp failed - abandoning';
	}
}

# Help
sub help {
	if (my $err=shift) {
		print $err, "\n";
		print "\n";
	}

	print 'Copies files to a series of robots.', "\n";
	print 'Usage: k3put ROBOT1 ROBOT2 ... FILE1 FILE2 ...', "\n";
	print '    +ROBOTx    Robot ID (e.g. 200), IP (e.g. 192.168.141.200) or name (e.g. bob)', "\n";
	print '    FILEy      File name (or folder name if a file with the same name exists in it)', "\n";
	exit(1);
}
