#! /usr/bin/perl
use strict;

# Include the k4-commons file
my $basepath=($0 =~ /(.*)\/(.*?)/)[0];
require $basepath.'/k4-commons', 'INCLUDED';

# Parse the command line
my @files;
while (my $cmd=shift) {
	if ($cmd =~ /^\+(.*)$/) {
		&robotlist_add($1);
	} else {
		$cmd=$1 if ($cmd =~ /^(.*)\/+$/);
		push @files, $cmd;
	}
}

# Prepare and check
my $user=$ENV{'USER'} || 'unknown_user';
my @robotlist=&robotlist_get();
&help('No robots specified.') if (! scalar @robotlist);
&help('No files specified.') if (! scalar @files);

# Retrieve the files
foreach my $robotip (@robotlist) {
	my $localfolder='k4-'.$robotip;
	mkdir $localfolder;
	foreach my $file (@files) {
		&print_and_execute('scp', '-r', 'root@'.$robotip.':~/'.$user.'/'.$file, $localfolder);
	}
}

# Help
sub help {
	if (my $err=shift) {
		print $err, "\n";
		print "\n";
	}

	print 'Copies files from robots and puts them in appropriate folders (k4-*).', "\n";
	print 'Usage: k4get +ROBOT1 +ROBOT2 ... FILE1 FILE2 ...', "\n";
	print '    +ROBOTx    Robot ID (e.g. 200), IP (e.g. 192.168.141.200) or name (e.g. bob)', "\n";
	print '    FILEy      file or folder to get from the robot (files with the same name will be silently overwritten on the computer)', "\n";
	exit(1);
}
