#
# (c) 2006 - 2008 EPFL, Lausanne, Switzerland
# Thomas Lochmatter
#

# The list of modules that this program needs
MODULES	:= odometry_track odometry_goto khepera4 i2cal commandline nmea

# The file name of the executable
TARGET	:= odometry_goto_timestamp

# If the K4_ROOT environment variable is set, you can comment out the following line
K4_ROOT	:= ../..

# Include the Makefile
include $(K4_ROOT)/Programs/Makefile.include
