#
# (c) 2006 - 2008 EPFL, Lausanne, Switzerland
# Thomas Lochmatter
#

# The list of modules that this program needs
MODULES	:= i2cal commandline measurement

# The file name of the executable
TARGET	:= i2c

# If the K4_ROOT environment variable is set, you can comment out the following line
K4_ROOT	:= ../..

# Include the Makefile
include $(K4_ROOT)/Programs/Makefile.include
