#
# (c) 2006 - 2008 EPFL, Lausanne, Switzerland
# Thomas Lochmatter
#

# The list of modules that this module needs
MODULES	:= kheptools khepera3 i2cal

# The file name of the archive
ARCHIVE	:= kheptools.a

# If the K3_ROOT environment variable is set, you can comment out the following line
K3_ROOT	:= ../..

# Include the Makefile
include $(K3_ROOT)/Modules/Makefilecpp.include
